---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  pre_tasks:
    - file: path=~/.ssh mode=0700 state=directory
    - lineinfile: dest=~/.ssh/known_hosts create=yes state=present line="{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}" regexp='^github.com'

  tasks:
    - name: generate ssh-key
      command: creates=~/.ssh/id_rsa ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ''

    - name: upgrade homebrew packages
      homebrew: update_homebrew=yes upgrade_all=yes

    - name: ensure taps are tapped.
      homebrew_tap: "tap={{ item }} state=present"
      with_items: "{{ brew_taps }}"

    # Brew
    - name: install homebrew packages
      homebrew: "name={{ brew_packages }} state=present"

    # Cask
    - name: install homebrew casks
      # Waits for https://github.com/ansible/ansible-modules-extras/pull/544
      #homebrew_cask: name={{item}} state=present install_options="appdir=homebrew_cask_appdir"
      homebrew_cask: name={{item}} state=present
      with_items: "{{ cask_packages }}"

    - name: install npm modules
      npm: name={{item}} global=yes
      with_items: "{{ npm_modules }}"
    - name: Install Visual Studio Code extensions
      command: code --install-extension {{item}}
      with_items: "{{ vscode_extensions }}"

    - name: remove outdated brew versions from the cellar
      command: brew cleanup

    - include: tasks/dotfiles.yml

    - include: tasks/vscode.yml
      vars:
        vscode_settingsdir: "~/Library/Application Support/Code/User"
        vscode_tmpdir: "~/vscode_old"

    - include: tasks/zsh.yml

    - name: Create folder for iterm related stuff
      file:
        path: "~/.iterm2"
        state: directory

    - name: Clone terminal themes
      ansible.builtin.git:
        repo: https://github.com/mbadolato/iTerm2-Color-Schemes
        dest: "~/.iterm2/iTerm2-Color-Schemes"

    - name: Clone city-lights theme
      ansible.builtin.git:
        repo: https://github.com/ruimarinho/iterm2-city-lights
        dest: "~/.iterm2/iterm2-city-lights"
