- name: Set ZSH as your default shell
  command: chsh -s /bin/zsh

- name: Clone Prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: "~/.zprezto"

# setopt EXTENDED_GLOB
# for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
#   ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
# done